apiVersion: v1
kind: Pod
metadata:
  name: parthm
spec:
  containers:
  - name: http-container
    image: httpd  # You can replace this with the image of your HTTP server
    ports:  
    - containerPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: http-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort